/**
 * Hand-crafted simulation of Nuxt full-stack output with preset: 'catalyst'.
 *
 * Demonstrates D1 (todos CRUD), KV (sessions), and R2 (file uploads)
 * all running entirely in the browser via CatalystWorkers.
 *
 * In a real Nuxt build, this would be generated by Nitro's rollup pipeline
 * using the @aspect/nitro-preset-catalyst entry point.
 */

async function handleRequest(request, env) {
  const url = new URL(request.url);
  const pathname = url.pathname;
  const method = request.method;

  // ── Page routes ──────────────────────────────────────────────────────
  if (pathname === '/' && method === 'GET') {
    return new Response(
      '<!DOCTYPE html><html><body><h1>Nuxt Todo App</h1><p>Running on Catalyst</p></body></html>',
      { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
    );
  }

  // ── D1 CRUD — Todos ─────────────────────────────────────────────────
  if (pathname === '/api/todos' && method === 'GET') {
    const result = await env.MY_DB.prepare('SELECT * FROM todos ORDER BY id').all();
    return new Response(JSON.stringify(result.results), {
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (pathname === '/api/todos' && method === 'POST') {
    const body = await request.json();
    await env.MY_DB
      .prepare('INSERT INTO todos (title, completed) VALUES (?, ?)')
      .bind(body.title, body.completed ? 1 : 0)
      .run();
    // Query for the last inserted row to get its actual ID
    const inserted = await env.MY_DB
      .prepare('SELECT * FROM todos ORDER BY id DESC LIMIT 1')
      .first();
    const id = inserted ? inserted.id : 0;
    return new Response(
      JSON.stringify({ id, title: body.title, completed: !!body.completed }),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    );
  }

  if (pathname === '/api/todos' && method === 'PUT') {
    const body = await request.json();
    await env.MY_DB
      .prepare('UPDATE todos SET title = ?, completed = ? WHERE id = ?')
      .bind(body.title, body.completed ? 1 : 0, body.id)
      .run();
    return new Response(JSON.stringify(body), {
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (pathname === '/api/todos' && method === 'DELETE') {
    const id = url.searchParams.get('id');
    await env.MY_DB.prepare('DELETE FROM todos WHERE id = ?').bind(Number(id)).run();
    return new Response(JSON.stringify({ deleted: true }), {
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // ── KV Sessions ─────────────────────────────────────────────────────
  if (pathname === '/api/session' && method === 'GET') {
    const key = url.searchParams.get('key');
    const value = await env.SESSION_KV.get(key);
    return new Response(JSON.stringify({ key, value }), {
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (pathname === '/api/session' && method === 'POST') {
    const body = await request.json();
    await env.SESSION_KV.put(body.key, body.value);
    return new Response(JSON.stringify({ stored: true }), {
      status: 201,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // ── R2 Uploads ──────────────────────────────────────────────────────
  if (pathname === '/api/upload' && method === 'POST') {
    const body = await request.json();
    await env.UPLOADS.put(body.key, body.data);
    return new Response(JSON.stringify({ uploaded: true, key: body.key }), {
      status: 201,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  if (pathname === '/api/upload' && method === 'GET') {
    const key = url.searchParams.get('key');
    const obj = await env.UPLOADS.get(key);
    if (!obj) {
      return new Response(JSON.stringify({ error: 'not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      });
    }
    const text = await obj.text();
    return new Response(JSON.stringify({ key, data: text }), {
      headers: { 'Content-Type': 'application/json' },
    });
  }

  return new Response('Not Found', { status: 404 });
}

// Workers module format entry point
export default {
  async fetch(request, env, ctx) {
    return handleRequest(request, env);
  },
};
