/**
 * Astro server entry for Catalyst runtime.
 *
 * This file is used by Astro's build system as the server entrypoint.
 * It wraps Astro's SSR App in the Workers module format (export default { fetch }).
 *
 * At build time, Astro bundles this with the application code.
 * The resulting bundle has:
 *   export default { fetch(request, env, ctx) { ... } }
 *
 * Bindings are accessible in Astro pages/endpoints via Astro.locals.catalyst.env.
 */

// @ts-ignore — resolved by Astro's build system
import { App } from 'astro/app';
// @ts-ignore — generated by Astro's build system
import { manifest } from ':astro-manifest';

let app: InstanceType<typeof App>;

function getApp() {
  if (!app) {
    app = new App(manifest);
  }
  return app;
}

export default {
  /**
   * Workers-compatible fetch handler.
   * Called by CatalystWorkers runtime for each matching request.
   */
  async fetch(
    request: Request,
    env: Record<string, unknown>,
    ctx?: { waitUntil?: (p: Promise<unknown>) => void },
  ): Promise<Response> {
    const astroApp = getApp();

    // Check if Astro handles this route
    const routeData = astroApp.match(request);
    if (!routeData) {
      return new Response('Not Found', { status: 404 });
    }

    // Inject Catalyst bindings into Astro.locals
    const locals = {
      catalyst: {
        env,
        ctx,
      },
    };

    try {
      return await astroApp.render(request, { routeData, locals });
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Internal Server Error';
      return new Response(message, {
        status: 500,
        headers: { 'Content-Type': 'text/plain' },
      });
    }
  },
};
