/**
 * Hand-crafted simulation of Nitro output with preset: 'catalyst'.
 *
 * Simulates what Nitro produces: a single ES module with export default { fetch }.
 * Routes, storage integration, and event.context.catalyst.env access.
 *
 * In a real Nitro build, this would be generated by Nitro's rollup pipeline
 * using the @aspect/nitro-preset-catalyst entry point.
 */

// Route handlers — simulates Nitro's H3 routing
const routeHandlers = {
  '/': async (_event) => {
    return new Response(
      '<!DOCTYPE html><html><body><h1>Hello from Nitro on Catalyst</h1></body></html>',
      {
        status: 200,
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      },
    );
  },

  '/api/hello': async (_event) => {
    return new Response(JSON.stringify({ hello: 'world' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  },

  '/api/env': async (event) => {
    // Demonstrates event.context.catalyst.env accessibility
    const env = event.context?.catalyst?.env ?? {};
    return new Response(
      JSON.stringify({
        hasEnv: !!event.context?.catalyst?.env,
        envKeys: Object.keys(env),
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      },
    );
  },

  '/api/storage': async (event) => {
    // Demonstrates useStorage integration via CatalystKV
    const storage = event.context?.catalyst?.env?.STORAGE;
    if (!storage) {
      return new Response(JSON.stringify({ error: 'no storage binding' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Write then read via the storage driver
    await storage.put('nitro-test-key', 'nitro-test-value');
    const value = await storage.get('nitro-test-key');

    return new Response(
      JSON.stringify({ written: true, readBack: value }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      },
    );
  },

  '/static/style.css': async (_event) => {
    // Simulates a static asset route coexisting with dynamic routes
    return new Response('body { color: red; }', {
      status: 200,
      headers: { 'Content-Type': 'text/css' },
    });
  },
};

// Workers module format entry point
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Build H3-like event context
    const event = {
      context: {
        catalyst: {
          env: env || {},
          ctx: ctx,
        },
      },
    };

    // Route matching
    const handler = routeHandlers[url.pathname];
    if (handler) {
      return handler(event);
    }

    // 404 for unmatched routes
    return new Response('Not Found', {
      status: 404,
      headers: { 'Content-Type': 'text/plain' },
    });
  },
};
